language: node_js

node_js:
  - '8'
  - '10'
  - '12'

before_script:
  - npm run bootstrap
  - COVERAGE=1 npm run build

after_success:
  - CODECOV_TOKEN="38b18ad2-deb9-4008-aa11-817605984656" npm run codecov
  - npm run coveralls

cache:
  directories:
    - node_modules

git:
  depth: 5
